// The furniture library's names in German and Turkish (spec 14d L8),
// by key; the categories by their English names.
import 'symbol_names.dart';

/// The names in German and Turkish (spec 14d L8); English is the asset's.
const SymbolNames furnitureSymbolNames = SymbolNames(
  names: {
    'de': {
      'dining.table.square.two': 'Quadratischer Esstisch, 2 Plätze',
      'dining.table.square.four': 'Quadratischer Esstisch, 4 Plätze',
      'dining.table.rect.four': 'Rechteckiger Esstisch, 4 Plätze',
      'dining.table.rect.six': 'Rechteckiger Esstisch, 6 Plätze',
      'dining.table.round': 'Runder Esstisch, 4 Plätze',
      'dining.chair': 'Esszimmerstuhl',
      'dining.bench': 'Sitzbank',
      'kitchen.base.300': 'Unterschrank 300',
      'kitchen.base.400': 'Unterschrank 400',
      'kitchen.base.600': 'Unterschrank 600',
      'kitchen.base.800': 'Unterschrank 800',
      'kitchen.sink': 'Spülenschrank',
      'kitchen.hob': 'Kochfeld',
      'kitchen.fridge': 'Kühlschrank',
      'kitchen.dishwasher': 'Geschirrspüler',
      'kitchen.washer': 'Waschmaschine',
      'kitchen.island': 'Kücheninsel',
      'bed.double.1400': 'Doppelbett 1400',
      'bed.double': 'Doppelbett',
      'bed.double.1800': 'Doppelbett 1800',
      'bed.single.800': 'Einzelbett 800',
      'bed.single': 'Einzelbett',
      'bed.single.1000': 'Einzelbett 1000',
      'bed.nightstand': 'Nachttisch',
      'bed.wardrobe.1200': 'Kleiderschrank 1200',
      'bed.wardrobe': 'Kleiderschrank',
      'bed.wardrobe.2400': 'Kleiderschrank 2400',
      'sofa.two': 'Zweisitzer-Sofa',
      'sofa.three': 'Dreisitzer-Sofa',
      'armchair': 'Sessel',
      'table.coffee': 'Couchtisch',
      'tv.unit': 'TV-Möbel',
      'bath.toilet': 'WC',
      'bath.washbasin': 'Waschbecken',
      'bath.tub': 'Badewanne',
      'bath.shower': 'Duschtasse',
      'office.desk.1200': 'Schreibtisch 1200',
      'office.desk': 'Schreibtisch',
      'office.desk.1600': 'Schreibtisch 1600',
      'office.chair': 'Bürostuhl',
      'office.bookshelf': 'Bücherregal',
    },
    'tr': {
      'dining.table.square.two': 'Kare yemek masası, 2 kişilik',
      'dining.table.square.four': 'Kare yemek masası, 4 kişilik',
      'dining.table.rect.four': 'Dikdörtgen yemek masası, 4 kişilik',
      'dining.table.rect.six': 'Dikdörtgen yemek masası, 6 kişilik',
      'dining.table.round': 'Yuvarlak yemek masası, 4 kişilik',
      'dining.chair': 'Yemek sandalyesi',
      'dining.bench': 'Bank',
      'kitchen.base.300': 'Alt dolap 300',
      'kitchen.base.400': 'Alt dolap 400',
      'kitchen.base.600': 'Alt dolap 600',
      'kitchen.base.800': 'Alt dolap 800',
      'kitchen.sink': 'Eviye dolabı',
      'kitchen.hob': 'Ocak',
      'kitchen.fridge': 'Buzdolabı',
      'kitchen.dishwasher': 'Bulaşık makinesi',
      'kitchen.washer': 'Çamaşır makinesi',
      'kitchen.island': 'Mutfak adası',
      'bed.double.1400': 'Çift kişilik yatak 1400',
      'bed.double': 'Çift kişilik yatak',
      'bed.double.1800': 'Çift kişilik yatak 1800',
      'bed.single.800': 'Tek kişilik yatak 800',
      'bed.single': 'Tek kişilik yatak',
      'bed.single.1000': 'Tek kişilik yatak 1000',
      'bed.nightstand': 'Komodin',
      'bed.wardrobe.1200': 'Gardırop 1200',
      'bed.wardrobe': 'Gardırop',
      'bed.wardrobe.2400': 'Gardırop 2400',
      'sofa.two': 'İkili kanepe',
      'sofa.three': 'Üçlü kanepe',
      'armchair': 'Koltuk',
      'table.coffee': 'Sehpa',
      'tv.unit': 'TV ünitesi',
      'bath.toilet': 'Klozet',
      'bath.washbasin': 'Lavabo',
      'bath.tub': 'Küvet',
      'bath.shower': 'Duş teknesi',
      'office.desk.1200': 'Çalışma masası 1200',
      'office.desk': 'Çalışma masası',
      'office.desk.1600': 'Çalışma masası 1600',
      'office.chair': 'Ofis sandalyesi',
      'office.bookshelf': 'Kitaplık',
    },
  },
  categories: {
    'de': {
      'Dining Room': 'Esszimmer',
      'Kitchen': 'Küche',
      'Bed Room': 'Schlafzimmer',
      'Living Room': 'Wohnzimmer',
      'Bathroom': 'Badezimmer',
      'Office': 'Büro',
    },
    'tr': {
      'Dining Room': 'Yemek odası',
      'Kitchen': 'Mutfak',
      'Bed Room': 'Yatak odası',
      'Living Room': 'Oturma odası',
      'Bathroom': 'Banyo',
      'Office': 'Ofis',
    },
  },
);
