/// Stable application identifier for anything the kernel exposes.
///
/// Real ids are UUIDs generated by the session layer (never by OCCT, which
/// has no identity facility). Extension types keep this zero-cost.
extension type const EntityId(String value) {
  String toJson() => value;
}

extension type const BodyId(String value) implements EntityId {}
extension type const FaceId(String value) implements EntityId {}
extension type const EdgeId(String value) implements EntityId {}
extension type const VertexId(String value) implements EntityId {}

/// Identifier of an [Operation] in a document's timeline. Monotonic per doc.
extension type const OpId(int value) {
  int toJson() => value;
}

enum EntityKind { body, face, edge, vertex }

/// Semantic record of one kernel entity: metadata only, never geometry.
class Entity {
  final EntityId id;
  final EntityKind kind;
  final String name;
  final BodyId? parent;

  const Entity({
    required this.id,
    required this.kind,
    required this.name,
    this.parent,
  });

  Map<String, Object?> toJson() => {
        'id': id.value,
        'kind': kind.name,
        'name': name,
        if (parent != null) 'parent': parent!.value,
      };

  factory Entity.fromJson(Map<String, Object?> json) => Entity(
        id: EntityId(json['id']! as String),
        kind: EntityKind.values.byName(json['kind']! as String),
        name: json['name']! as String,
        parent:
            json['parent'] == null ? null : BodyId(json['parent']! as String),
      );

  @override
  bool operator ==(Object other) =>
      other is Entity &&
      other.id == id &&
      other.kind == kind &&
      other.name == name &&
      other.parent == parent;

  @override
  int get hashCode => Object.hash(id, kind, name, parent);

  @override
  String toString() => 'Entity(${kind.name} ${id.value} "$name")';
}

/// Old id -> new ids table returned by every modeling operation.
/// An empty list means the old entity was consumed/deleted.
class IdRemap {
  final Map<EntityId, List<EntityId>> mapping;

  const IdRemap(this.mapping);

  static const IdRemap empty = IdRemap({});

  Map<String, Object?> toJson() => {
        for (final e in mapping.entries)
          e.key.value: [for (final id in e.value) id.value],
      };

  factory IdRemap.fromJson(Map<String, Object?> json) => IdRemap({
        for (final e in json.entries)
          EntityId(e.key): [
            for (final v in e.value! as List) EntityId(v as String),
          ],
      });
}
