// The restaurant library's names in German and Turkish (spec 14d L8), by
// key; the categories by their English names.
import 'package:jet_cad_floor_plan/symbol_sources.dart';

/// The names in German and Turkish (spec 14d L8); English is the asset's.
const SymbolNames restaurantSymbolNames = SymbolNames(
  names: {
    'de': {
      'restaurant.table.square.two': 'Quadratischer Tisch, 2 Plätze',
      'restaurant.table.square.four': 'Quadratischer Tisch, 4 Plätze',
      'restaurant.table.rect.four': 'Rechteckiger Tisch, 4 Plätze',
      'restaurant.table.rect.six': 'Rechteckiger Tisch, 6 Plätze',
      'restaurant.table.rect.eight': 'Rechteckiger Tisch, 8 Plätze',
      'restaurant.table.rect.ten': 'Rechteckiger Tisch, 10 Plätze',
      'restaurant.table.rect.twelve': 'Rechteckiger Tisch, 12 Plätze',
      'restaurant.table.round.two': 'Runder Tisch, 2 Plätze',
      'restaurant.table.round.four': 'Runder Tisch, 4 Plätze',
      'restaurant.table.round.six': 'Runder Tisch, 6 Plätze',
      'restaurant.table.round.eight': 'Runder Tisch, 8 Plätze',
      'restaurant.table.round.ten': 'Runder Tisch, 10 Plätze',
      'restaurant.booth.two': 'Sitznische, 2 Plätze',
      'restaurant.booth.four': 'Sitznische, 4 Plätze',
      'restaurant.booth.six': 'Sitznische, 6 Plätze',
      'restaurant.booth.corner': 'Ecksitznische, 5 Plätze',
      'restaurant.booth.round': 'Runde Sitznische, 6 Plätze',
      'restaurant.banquette.two': 'Sitzbank, 2 Plätze',
      'restaurant.banquette.four': 'Sitzbank, 4 Plätze',
      'restaurant.lounge.four': 'Lounge-Gruppe, 4 Plätze',
      'restaurant.lounge.two': 'Lounge-Gruppe, 2 Plätze',
      'restaurant.bar.stool': 'Barhocker',
      'restaurant.bar.table.high.two': 'Stehtisch, 2 Hocker',
      'restaurant.bar.table.high.four': 'Stehtisch, 4 Hocker',
      'restaurant.bar.table.ledge': 'Barablage, 4 Hocker',
      'restaurant.bar.counter': 'Bartheke',
      'restaurant.bar.counter.corner': 'Eck-Bartheke',
      'restaurant.bar.counter.u': 'U-Bartheke',
      'restaurant.bar.back': 'Rückbuffet',
      'restaurant.bar.taps': 'Zapfanlage',
      'restaurant.cashier': 'Kassentisch',
      'restaurant.host.stand': 'Empfangspult',
      'restaurant.pos.terminal': 'Kassenterminal',
      'restaurant.service.station': 'Servicestation',
      'restaurant.buffet': 'Buffettheke',
      'restaurant.salad.bar': 'Salatbar',
      'restaurant.dessert.display': 'Dessertvitrine',
      'restaurant.drinks.fridge': 'Getränkekühlschrank',
      'restaurant.coffee.station': 'Kaffeestation',
      'restaurant.service.cart': 'Servierwagen',
      'restaurant.tray.stand': 'Tablettständer',
      'restaurant.highchair': 'Hochstuhl',
      'restaurant.waiting.bench': 'Wartebank',
      'restaurant.coat.rack': 'Garderobe',
      'restaurant.kitchen.pass': 'Küchenpass',
      'restaurant.kitchen.prep.table': 'Vorbereitungstisch',
      'restaurant.kitchen.range.four': 'Herd, 4 Flammen',
      'restaurant.kitchen.range.six': 'Herd, 6 Flammen',
      'restaurant.kitchen.fryer': 'Fritteuse',
      'restaurant.kitchen.griddle': 'Grillplatte',
      'restaurant.kitchen.oven.convection': 'Heißluftofen',
      'restaurant.kitchen.oven.pizza': 'Pizzaofen',
      'restaurant.kitchen.dishwasher': 'Geschirrspüler',
      'restaurant.kitchen.sink.three': 'Dreifach-Spülbecken',
      'restaurant.kitchen.sink.hand': 'Handwaschbecken',
      'restaurant.kitchen.fridge.reachin': 'Standkühlschrank',
      'restaurant.kitchen.freezer': 'Tiefkühlschrank',
      'restaurant.kitchen.walkin': 'Kühlzelle',
      'restaurant.kitchen.shelving': 'Regal',
      'restaurant.kitchen.ice.machine': 'Eismaschine',
      'restaurant.kitchen.bin': 'Abfallbehälter',
      'restaurant.parasol': 'Sonnenschirm',
      'restaurant.heater': 'Heizstrahler',
      'restaurant.planter.round': 'Runder Pflanzkübel',
      'restaurant.planter.long': 'Langer Pflanzkübel',
      'restaurant.partition': 'Trennwand',
      'restaurant.stage': 'Bühne',
      'restaurant.dj.booth': 'DJ-Pult',
      'restaurant.piano': 'Flügel',
    },
    'tr': {
      'restaurant.table.square.two': 'Kare masa, 2 kişilik',
      'restaurant.table.square.four': 'Kare masa, 4 kişilik',
      'restaurant.table.rect.four': 'Dikdörtgen masa, 4 kişilik',
      'restaurant.table.rect.six': 'Dikdörtgen masa, 6 kişilik',
      'restaurant.table.rect.eight': 'Dikdörtgen masa, 8 kişilik',
      'restaurant.table.rect.ten': 'Dikdörtgen masa, 10 kişilik',
      'restaurant.table.rect.twelve': 'Dikdörtgen masa, 12 kişilik',
      'restaurant.table.round.two': 'Yuvarlak masa, 2 kişilik',
      'restaurant.table.round.four': 'Yuvarlak masa, 4 kişilik',
      'restaurant.table.round.six': 'Yuvarlak masa, 6 kişilik',
      'restaurant.table.round.eight': 'Yuvarlak masa, 8 kişilik',
      'restaurant.table.round.ten': 'Yuvarlak masa, 10 kişilik',
      'restaurant.booth.two': 'Loca, 2 kişilik',
      'restaurant.booth.four': 'Loca, 4 kişilik',
      'restaurant.booth.six': 'Loca, 6 kişilik',
      'restaurant.booth.corner': 'Köşe loca, 5 kişilik',
      'restaurant.booth.round': 'Yuvarlak loca, 6 kişilik',
      'restaurant.banquette.two': 'Bank koltuk, 2 kişilik',
      'restaurant.banquette.four': 'Bank koltuk, 4 kişilik',
      'restaurant.lounge.four': 'Lounge takımı, 4 kişilik',
      'restaurant.lounge.two': 'Lounge takımı, 2 kişilik',
      'restaurant.bar.stool': 'Bar taburesi',
      'restaurant.bar.table.high.two': 'Yüksek masa, 2 tabureli',
      'restaurant.bar.table.high.four': 'Yüksek masa, 4 tabureli',
      'restaurant.bar.table.ledge': 'Bar rafı, 4 tabureli',
      'restaurant.bar.counter': 'Bar tezgâhı',
      'restaurant.bar.counter.corner': 'Köşe bar tezgâhı',
      'restaurant.bar.counter.u': 'U bar tezgâhı',
      'restaurant.bar.back': 'Arka bar',
      'restaurant.bar.taps': 'Bira muslukları',
      'restaurant.cashier': 'Kasa',
      'restaurant.host.stand': 'Karşılama standı',
      'restaurant.pos.terminal': 'POS terminali',
      'restaurant.service.station': 'Servis istasyonu',
      'restaurant.buffet': 'Büfe tezgâhı',
      'restaurant.salad.bar': 'Salata barı',
      'restaurant.dessert.display': 'Tatlı vitrini',
      'restaurant.drinks.fridge': 'İçecek dolabı',
      'restaurant.coffee.station': 'Kahve istasyonu',
      'restaurant.service.cart': 'Servis arabası',
      'restaurant.tray.stand': 'Tepsi sehpası',
      'restaurant.highchair': 'Mama sandalyesi',
      'restaurant.waiting.bench': 'Bekleme bankı',
      'restaurant.coat.rack': 'Portmanto',
      'restaurant.kitchen.pass': 'Pas tezgâhı',
      'restaurant.kitchen.prep.table': 'Hazırlık tezgâhı',
      'restaurant.kitchen.range.four': 'Ocak, 4 gözlü',
      'restaurant.kitchen.range.six': 'Ocak, 6 gözlü',
      'restaurant.kitchen.fryer': 'Fritöz',
      'restaurant.kitchen.griddle': 'Izgara plakası',
      'restaurant.kitchen.oven.convection': 'Konveksiyonlu fırın',
      'restaurant.kitchen.oven.pizza': 'Pizza fırını',
      'restaurant.kitchen.dishwasher': 'Bulaşık makinesi',
      'restaurant.kitchen.sink.three': 'Üç gözlü eviye',
      'restaurant.kitchen.sink.hand': 'El yıkama lavabosu',
      'restaurant.kitchen.fridge.reachin': 'Dik tip buzdolabı',
      'restaurant.kitchen.freezer': 'Derin dondurucu',
      'restaurant.kitchen.walkin': 'Soğuk oda',
      'restaurant.kitchen.shelving': 'Raf',
      'restaurant.kitchen.ice.machine': 'Buz makinesi',
      'restaurant.kitchen.bin': 'Çöp kutusu',
      'restaurant.parasol': 'Şemsiye',
      'restaurant.heater': 'Dış mekân ısıtıcısı',
      'restaurant.planter.round': 'Yuvarlak saksı',
      'restaurant.planter.long': 'Uzun saksı',
      'restaurant.partition': 'Bölme',
      'restaurant.stage': 'Sahne',
      'restaurant.dj.booth': 'DJ kabini',
      'restaurant.piano': 'Kuyruklu piyano',
    },
  },
  categories: {
    'de': {
      'Restaurant Tables': 'Restauranttische',
      'Booths and Lounge': 'Sitznischen und Lounge',
      'Bar': 'Bar',
      'Service': 'Service',
      'Commercial Kitchen': 'Gewerbeküche',
      'Outdoor and Decor': 'Außenbereich und Deko',
    },
    'tr': {
      'Restaurant Tables': 'Restoran masaları',
      'Booths and Lounge': 'Localar ve lounge',
      'Bar': 'Bar',
      'Service': 'Servis',
      'Commercial Kitchen': 'Endüstriyel mutfak',
      'Outdoor and Decor': 'Dış mekân ve dekor',
    },
  },
);
